version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MONGO_URI=mongodb://mongo:27017
      - DB_NAME=mychat
      - JWT_SECRET=my_super_secret_jwt_key
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
